[package]
name = "essentials-of-comp"
version = "0.1.0"
edition = "2021"

[dependencies]
allocator-api2 = { version = "0.3.1", default-features = false }

[patch.crates-io]
allocator-api2 = { path = "./vendor/allocator-api2" }
